apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: redis-master
      redis-sentinel: "true"
      redis-master: "true"
      role: master
    name: redis-master
  spec:
    replicas: 1
    selector:
      app: redis-master
      redis-sentinel: "true"
      redis-master: "true"
      role: master
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: redis-master
          redis-sentinel: "true"
          redis-master: "true"
          role: master
      spec:
        containers:
        - image: 172.30.151.14:5000/redis/redis@sha256:e508f686a4f50eb54350c091f3df8fc6a9649dd8c613482088534c5ca70cfc37
          imagePullPolicy: Always
          name: redis
          env:
            - name: MASTER
              value: "true"  
          volumeMounts:
            - mountPath: /redis-master-data
              name: data 
          ports:
            - containerPort: 6379
          resources: {}
        - image: 172.30.151.14:5000/redis/redis@sha256:e508f686a4f50eb54350c091f3df8fc6a9649dd8c613482088534c5ca70cfc37
          imagePullPolicy: Always
          name: sentinel
          resources: {}
          ports:
            - containerPort: 26379
          env:
            - name: SENTINEL
              value: "true"   
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: data
            emptyDir: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:latest
          namespace: redis
      type: ImageChange
  status: {}
kind: List
metadata: {}
