apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: sentry-metrics
  name: sentry-metrics
  namespace: sentry
spec:
  replicas: 1
  selector:
    app: sentry-metrics
    deploymentconfig: sentry-metrics
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: sentry-metrics
        deploymentconfig: sentry-metrics
    spec:
      containers:
        - name: sentry-metrics
          image: docker.io/prom/statsd-exporter:v0.10.5
          imagePullPolicy: IfNotPresent
          args:
          - "--statsd.listen-udp=:9125"
          - "--web.listen-address=:9102"
          ports:
            - containerPort: 9125
              name: statsd
            - containerPort: 9102
              name: metrics
            initialDelaySeconds: 50
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30