apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9102"
    prometheus.io/scrape: "true"
  labels:
    app: sentry-metrics
  name: sentry-metrics
  namespace: sentry
spec:
  ports:
  - port: 9102
    targetPort: 9102
    protocol: TCP
    name: metrics
  - port: 9125
    targetPort: 9125
    protocol: UDP
    name: statsd
  selector:
    deploymentconfig: sentry-metrics
  sessionAffinity: None
  type: ClusterIP